feature (ICONS): agregar aliases para otros usos
andes/andes-font-icon pull request #1
Opened 2019-08-23 13:39 UTC by andrrrl

- más fácil de mantener
- se entiende mejor su uso
- TODO: se podrían usar variables SCSS para los códigos

2019-08-23 14:55 UTC, liquid36 commented
Bot, ese archivo se pisa con cada publicacion de fontastic. No sirve agregar alias ahí.
Hay que armar algo desde fontello o fontastic o desde la herramienta que hace la importación.

2019-08-23 14:56 UTC, liquid36 requested changes
Hola!

2019-08-23 14:58 UTC, liquid36 commented
El algoritmo tiene que ser alias de nombres, porque no sabemos si el caracter interno puede cambiar o no en cada publicaicón.

2020-07-29 15:02 UTC, closed without merging

2020-07-29 15:02 UTC, andrrrl commented
Se cierra nomás...